/datum/planet
	var/list/coldest_biomes
	var/list/cold_biomes
	var/list/warm_biomes
	var/list/hot_biomes
	var/list/coldest_cave_biomes
	var/list/cold_cave_biomes
	var/list/warm_cave_biomes
	var/list/hot_cave_biomes
